### ISSUE TITLE
Silence openssl warnings

### ISSUE THREAD

**Issue by oksijun** [murgo/IrssiNotifier#197]
With openssl 1.1.1 (not sure which previous versions caused the same error, if any) I get warnings such as this: 

```
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
```
It seems that adding -iter 10000 or something similar to the openssl invocation in irssinotifier.pl fixes this.

I didn't find much information about these two options, but https://www.guyrutenberg.com/2015/09/07/default-pbkdf2-iteration-count-for-encrypted-keys-generated-by-openssl/ seems to indicate that 2048 would be the default number of iterations (when using -pbkdf2 without specifying -iter (?)), and that 10000 could be a reasonable value to use.

In any case the warnings interfere with the input area in irssi, so this would be worth fixing I think.

**Comment by fulafisken** [comment]
I modyfied line 339 to look like this and got rid of the message.
    my $pid = open2(my $out, my $in, qw(openssl enc -aes-128-cbc -iter 10000 -base64 -md md5 -A -pass), "fd:$rfn");

**Comment by murgo** [comment]
I didn't have these errors myself, probably because my OpenSSL is not latest. For time being the OpenSSL errors are currently thrown straight to /dev/null in the latest script. See website for update info.

It would probably be better to actually replace the currently used AES-128 with something that is not deprecated, though AES-128 is still not "broken" as far as I know.

PR for using better encryption/decryption with OpenSSL and Android respectively would be appreciated :)
